datesofinterest<-c("1/2/2007", "2/2/2007")
fulldata <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
filtereddata <- fulldata[fulldata$Date %in% datesofinterest,]
filtereddata$datetime <- strptime(paste(filtereddata$Date, filtereddata$Time), "%d/%m/%Y %H:%M:%S")
png(file="plot3.png", width=480, height=480, bg="transparent")
with (filtereddata, plot(datetime, Sub_metering_1, type="l", xlab ="", ylab="Energy sub metering", col="black"))
with (filtereddata, lines(datetime, Sub_metering_2, col="red"))
with (filtereddata, lines(datetime, Sub_metering_3, col="blue"))
legend("topright", col=c("black", "red", "blue"), lwd = 1, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()